version: '3'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: es
    ports:
      - 0.0.0.0:9200:9200
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdb:/usr/share/elasticsearch/data
    restart: always
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    container_name: kibana
    ports:
      - 127.0.0.1:5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://es:9200
    depends_on:
      - es
    restart: always
volumes:
  esdb:
